unique_ids:
  assets: {}
  forms:
    home: '1735589044238981942969535.0654'
  modules:
    components: R3AYGJBS2OPZIWRCOTW466MFOPMSRWK6
    components.charts: 6RPKJH4W54IXMWKB4BJOLRTBQHXWZUBV
    utils: U6Q3EPFTXRAOF3XOTFG56ZWKKLJYUEPY
    utils.placeholder: '1735588895907929490218894.5417'
  scripts:
    worker_call: 6TLNS5QE3LFUAAZSA264VFUESMGJ3OOT
  server_modules:
    _config: DUITOPN3PO3QEZB5MKK7YZLARNFUJWXK
    api: HUYVEEG4SX7OGMLK3KDBZ5D3UGW7KC32
    api.nest: 5LGLFDAJGIXSZAYKQMKMBKL42PJUHYIE
    api.nest.auth: HKUAQTT6VWK45QHUHRJGOYVZOSCCDKTC
    api.nest.thermostat: AYPYAE735FWRO45HDCW2YB7VLMIMR2WO
    api.openweather: Y65UPXFL2PPTQ7WELJWUWNXG4DFEN2TI
    api.openweather.weather: VFRYENXLJO2ABAOH4OHUXQCBIBQZYWM2
    core: VWOF4MDIJSDCHFGD4Y5FX6JXV5VVIPGL
    core.temperature: DPCP6YLNCNDRCZO52IF6ZVCZUTWWLKX5
    core.timers: WVCJGDY5S2MNZ7Y6Z3XZFVNRU3EZ7W4G
    data: BVVJEGJC6COAD5GXIGKI5OMYSFLCDPJT
    data.database: YQBSUTD66XNP7LEEI2HOHQL7HBFT6LI7
    utils: L5DV57EMHMLWVZQ3OAYO6HXKADV774XD
    utils.time: SFZO2D3GWOEZ223VY74FFUVG7CVCYVOJ
