color_scheme:
  colors:
  - {color: '#D0BCFF', name: Primary}
  - {color: '#4F378B', name: Primary Container}
  - {color: '#381E72', name: On Primary}
  - {color: '#EADDFF', name: On Primary Container}
  - {color: '#CCC2DC', name: Secondary}
  - {color: '#4A4458', name: Secondary Container}
  - {color: '#332D41', name: On Secondary}
  - {color: '#E8DEF8', name: On Secondary Container}
  - {color: '#EFB8C8', name: Tertiary}
  - {color: '#633B48', name: Tertiary Container}
  - {color: '#492532', name: On Tertiary}
  - {color: '#FFD8E4', name: On Tertiary Container}
  - {color: '#F2B8B5', name: Error}
  - {color: '#1C1B1F', name: Background}
  - {color: '#111412', name: Surface}
  - {color: '#E1E3DF', name: On Background}
  - {color: '#C5C7C3', name: On Surface}
  - {color: '#404943', name: Surface Variant}
  - {color: '#C0C9C1', name: On Surface Variant}
  - {color: '#8A938C', name: Outline}
  - {color: 'rgba(230, 224, 233, 0.38)', name: On Disabled}
  - {color: 'rgba(230, 224, 233, 0.12)', name: Disabled Container}
  - {color: 'rgba(230, 224, 233, 0.08)', name: Light Overlay 1}
  - {color: 'rgba(230, 224, 233, 0.12)', name: Light Overlay 2}
  - {color: 'rgba(230, 224, 233, 0.08)', name: Dark Overlay 1}
  - {color: 'rgba(230, 224, 233, 0.12)', name: Dark Overlay 2}
  - {color: 'rgba(208, 188, 255, 0.05)', name: Primary Overlay 1}
  - {color: 'rgba(208, 188, 255, 0.08)', name: Primary Overlay 2}
  - {color: 'rgba(208, 188, 255, 0.11)', name: Primary Overlay 3}
  - {color: '#49454F', name: Outline Variant}
  - {color: '#601410', name: On Error}
  - {color: '#1D1B20', name: Surface Container Low}
  - {color: '#2B2930', name: Surface Container High}
  - {color: '#36343B', name: Surface Container Highest}
  - {color: 'rgba(230, 224, 233, 0.04)', name: Disabled Container 2}
  - {color: 'rgba(242, 184, 181, 0.08)', name: Error Overlay 1}
  - {color: 'rgba(242, 184, 181, 0.12)', name: Error Overlay 2}
  - {color: 'rgba(230, 224, 233,0.16)', name: Dark Overlay 3}
  - {color: '#F9DEDC', name: On Error Container}
  - {color: '#211F26', name: Surface Container}
  - {color: '#E6E0E9', name: Inverse Surface}
  - {color: '#322F35', name: Inverse On Surface}
  - {color: 'rgba(202,196,208, 0.08)', name: On Surface Variant Overlay 1}
  - {color: 'rgba(202,196,208, 0.12)', name: On Surface Variant Overlay 2}
  - {color: 'rgba(50,47,53, 0.08)', name: Inverse On Surface Overlay 1}
  - {color: 'rgba(50,47,53, 0.12)', name: Inverse On Surface Overlay 2}
  preset_groups: []
roles: []
