# .github/workflows/nest-monitor.yml
name: Nest Temperature Monitor
on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  collect-temp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anvil-uplink
          pip install -e .

      - name: Run nest monitor
        env:
          ANVIL_UPLINK_KEY: ${{ secrets.ANVIL_UPLINK_KEY }}
        working-directory: nest_monitor
        run: python worker.py
